version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=scod jcyo xrjb bxgc
      - MAIL_USERNAME=pdhileepkumar003@gmail.com
      - MAIL_PASSWORD=scod jcyo xrjb bxgc
      - DB_USER=postgres
      - DB_PASS=DatabasePwd
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=smartmail
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DatabasePwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
